[package]
name = "fs-sort"
version = "0.1.0"
edition = "2021"

[dependencies]
notify = "6.1.1"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.40.0", features = ["full"] }
toml = "0.8.19"
validator = { version = "0.18.1", features = ["derive"] }
