[package]
name = "fs-sort"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.19"
validator = { version = "0.18.1", features = ["derive"] }
